export const Kailuo_0821=[
    {
        id:1, // 编号
        name:'波波洛利', //名称
        attribute:'', //属性
        shape:'S', //体型
        hp:'F', //血量
        sp:'E', //疲劳值
        attack:'F',//攻击
        guard:'F', //防御
        speed:'F', //速度
        wisdom:'E',//智力
        skill:'',  //技能
        skill_docs:'',//技能说明
        evolve:6,    //进化
        evolveTwo:19,//最终进化
        vestigial:'',//由谁进化
        vestigialTwo:'',//由谁孵化
        min_green:0,
        max_green:500,
        min_red:0,
        max_red:500,
        min_blue:0,
        max_blue:500,
        min_purple:0,
        max_purple:500,
        min_yello:0,
        max_yello:500,
        min_black:0,
        max_black:500
    },
    {
        id:2,name:'梅塔可',attribute:'',shape:'S',
        hp:'F',sp:'D',attack:'F',guard:'F',speed:'F',wisdom:'E',
        skill:'加速之速1',skill_docs:'',
        evolve:'11',evolveTwo:'13',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:15,max_blue:200,min_purple:4,max_purple:95,
        min_yello:0,max_yello:95,min_black:0,max_black:0
    },
    {
        id:3,name:'小海蛇',attribute:'',shape:'S',
        hp:'F',sp:'E',attack:'F',guard:'F',speed:'F',wisdom:'F',
        skill:'水平攻击1',skill_docs:'',
        evolve:'35',evolveTwo:'69',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:18,max_blue:200,min_purple:5,max_purple:98,
        min_yello:0,max_yello:98,min_black:0,max_black:0
    },
    {
        id:4,name:'淡黄水母',attribute:'水',shape:'S',
        hp:'F',sp:'F',attack:'E',guard:'E',speed:'E',wisdom:'E',
        skill:'加速之术1',skill_docs:'',
        evolve:'14',evolveTwo:'46',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:90,min_red:1,max_red:90,
        min_blue:1,max_blue:90,min_purple:6,max_purple:90,
        min_yello:10,max_yello:200,min_black:1,max_black:90
    },
    {
        id:5,name:'加布龙头鱼',attribute:'水',shape:'S',
        hp:'E',sp:'E',attack:'E',guard:'E',speed:'E',wisdom:'E',
        skill:'连击a',skill_docs:'',
        evolve:'27',evolveTwo:'45',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:15,max_blue:200,min_purple:4,max_purple:95,
        min_yello:0,max_yello:95,min_black:0,max_black:0
    },
    {
        id:6,name:'水滴君',attribute:'水',shape:'S',
        hp:'F',sp:'D',attack:'F',guard:'E',speed:'E',wisdom:'E',
        skill:'HP回复1',skill_docs:'',
        evolve:'19',evolveTwo:'52',vestigial:'',vestigialTwo:'',
        min_green:19,max_green:200,min_red:9,max_red:95,
        min_blue:0,max_blue:95,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:7,name:'乌贼鲁塔',attribute:'水',shape:'S',
        hp:'F',sp:'E',attack:'F',guard:'E',speed:'E',wisdom:'D',
        skill:'连击a',skill_docs:'',
        evolve:'24',evolveTwo:'34',vestigial:'',vestigialTwo:'',
        min_green:8,max_green:94,min_red:9,max_red:94,
        min_blue:4,max_blue:94,min_purple:14,max_purple:200,
        min_yello:8,max_yello:94,min_black:4,max_black:94
    },
    {
        id:8,name:'卡布林贝',attribute:'水',shape:'S',
        hp:'E',sp:'F',attack:'F',guard:'E',speed:'F',wisdom:'E',
        skill:'HP回复术1',skill_docs:'',
        evolve:'17',evolveTwo:'31',vestigial:'',vestigialTwo:'',
        min_green:19,max_green:200,min_red:11,max_red:99,
        min_blue:1,max_blue:99,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:9,name:'针左卫门',attribute:'水',shape:'S',
        hp:'E',sp:'C',attack:'E',guard:'E',speed:'E',wisdom:'E',
        skill:'水平攻击1',skill_docs:'',
        evolve:'39',evolveTwo:'62',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:28,max_blue:200,min_purple:8,max_purple:98,
        min_yello:2,max_yello:98,min_black:0,max_black:0
    },
    {
        id:10,name:'奇酷虾',attribute:'火',shape:'S',
        hp:'E',sp:'E',attack:'D',guard:'E',speed:'E',wisdom:'E',
        skill:'水平攻击1',skill_docs:'',
        evolve:'26',evolveTwo:'42',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:22,max_red:200,
        min_blue:13,max_blue:92,min_purple:1,max_purple:92,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:11,name:'哔哩兔',attribute:'雷',shape:'S',
        hp:'F',sp:'B',attack:'F',guard:'E',speed:'E',wisdom:'E',
        skill:'加速之术1',skill_docs:'',
        evolve:'13',evolveTwo:'29',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:26,max_red:200,
        min_blue:15,max_blue:96,min_purple:1,max_purple:96,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:12,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:13,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:14,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:15,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:16,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:17,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:18,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:19,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:20,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:21,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:22,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:23,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:24,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:25,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:26,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:27,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:28,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:29,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:30,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:31,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:32,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:33,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:34,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:35,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:36,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:37,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:38,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:39,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:40,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:41,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:42,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:43,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:44,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:45,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:46,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:47,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:48,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:49,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:50,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:51,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:52,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:53,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:54,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:55,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:56,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:57,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:58,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:59,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:60,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:61,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:62,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:63,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:64,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:65,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:66,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:67,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:68,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:69,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:70,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:71,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:72,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:73,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:74,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:75,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:76,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:77,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:78,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:79,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:80,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:81,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:82,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:83,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:84,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:85,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:86,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:87,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:88,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:89,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:90,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:91,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:92,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:93,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:94,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:95,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:96,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:97,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:98,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:99,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:100,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:101,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:102,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:103,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:104,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:105,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:106,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:107,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:108,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:109,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:110,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:111,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:112,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:113,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:114,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:115,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:116,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:117,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:118,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:119,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:120,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:121,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:122,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:123,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:124,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:125,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:126,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:127,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:128,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:129,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:130,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:131,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:132,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:133,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:134,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:135,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:136,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:137,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:138,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:139,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:140,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:141,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:142,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:143,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:144,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:145,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:146,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:147,name:'发仙人改',attribute:'雷',shape:'M',
        hp:'A',sp:'E',attack:'A',guard:'B',speed:'S',wisdom:'A',
        skill:'水平攻击3',skill_docs:'',
        evolve:'158',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:34,max_green:298,min_red:49,max_red:398,
        min_blue:49,max_blue:398,min_purple:205,max_purple:398,
        min_yello:338,max_yello:500,min_black:49,max_black:398
    },
    {
        id:148,name:'家布龙先生改',attribute:'',shape:'M',
        hp:'A',sp:'F',attack:'A',guard:'A',speed:'A',wisdom:'B',
        skill:'连击2',skill_docs:'',
        evolve:'164',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:70,max_green:398,min_red:49,max_red:398,
        min_blue:0,max_blue:0,min_purple:49,max_purple:398,
        min_yello:70,max_yello:398,min_black:338,max_black:500
    },
    {
        id:149,name:'六角恐龙改',attribute:'雷',shape:'S',
        hp:'A',sp:'A',attack:'A',guard:'A',speed:'A',wisdom:'B',
        skill:'究极攻击2',skill_docs:'',
        evolve:'157',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:210,max_green:400,min_red:210,max_red:400,
        min_blue:105,max_blue:400,min_purple:350,max_purple:500,
        min_yello:214,max_yello:400,min_black:105,max_black:400
    },
    {
        id:150,name:'骨子船长改',attribute:'暗',shape:'S',
        hp:'A',sp:'A',attack:'S',guard:'A',speed:'A',wisdom:'B',
        skill:'水平攻击3',skill_docs:'',
        evolve:'167',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:72,max_green:394,min_red:50,max_red:394,
        min_blue:0,max_blue:0,min_purple:50,max_purple:394,
        min_yello:72,max_yello:394,min_black:344,max_black:500
    },
    {
        id:151,name:'多训犬改',attribute:'火',shape:'M',
        hp:'A',sp:'C',attack:'A',guard:'A',speed:'A',wisdom:'B',
        skill:'水平攻击2',skill_docs:'',
        evolve:'168',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:35,max_red:198,
        min_blue:72,max_blue:398,min_purple:348,max_purple:500,
        min_yello:35,max_yello:198,min_black:0,max_black:0
    },
    {
        id:152,name:'红龙小助改',attribute:'火',shape:'M',
        hp:'A',sp:'D',attack:'S',guard:'A',speed:'A',wisdom:'B',
        skill:'究极攻击2',skill_docs:'',
        evolve:'168',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:355,max_red:500,
        min_blue:213,max_blue:395,min_purple:35,max_purple:195,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:153,name:'哔哩可改',attribute:'火',shape:'M',
        hp:'A',sp:'F',attack:'A',guard:'A',speed:'A',wisdom:'A',
        skill:'究极攻击2',skill_docs:'',
        evolve:'164',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:35,max_green:298,min_red:51,max_red:398,
        min_blue:51,max_blue:398,min_purple:214,max_purple:398,
        min_yello:358,max_yello:500,min_black:51,max_black:398
    },
    {
        id:154,name:'磬石花改',attribute:'',shape:'M',
        hp:'A',sp:'F',attack:'S',guard:'A',speed:'A',wisdom:'B',
        skill:'加速之术3',skill_docs:'',
        evolve:'156',evolveTwo:'167',vestigial:'',vestigialTwo:'',
        min_green:359,max_green:500,min_red:215,max_red:399,
        min_blue:35,max_blue:199,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:155,name:'丸太君改',attribute:'暗',shape:'S',
        hp:'A',sp:'E',attack:'A',guard:'B',speed:'S',wisdom:'A',
        skill:'水平攻击3',skill_docs:'',
        evolve:'162',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:37,max_green:298,min_red:53,max_red:398,
        min_blue:53,max_blue:398,min_purple:220,max_purple:398,
        min_yello:368,max_yello:500,min_black:53,max_black:398
    },
    {
        id:156,name:'岩魔人',attribute:'',shape:'M',
        hp:'A',sp:'A',attack:'A',guard:'A',speed:'A',wisdom:'A',
        skill:'',skill_docs:'',
        evolve:'167',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:226,max_green:397,min_red:226,max_red:397,
        min_blue:113,max_blue:397,min_purple:377,max_purple:500,
        min_yello:226,max_yello:397,min_black:113,max_black:397
    },
    {
        id:157,name:'炽热魔人',attribute:'火',shape:'M',
        hp:'A',sp:'A',attack:'S',guard:'A',speed:'A',wisdom:'B',
        skill:'水平攻击3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:226,max_green:397,min_red:226,max_red:397,
        min_blue:113,max_blue:397,min_purple:377,max_purple:500,
        min_yello:226,max_yello:397,min_black:113,max_black:397
    },
    {
        id:158,name:'棉花糖大王改',attribute:'',shape:'M',
        hp:'A',sp:'E',attack:'A',guard:'A',speed:'S',wisdom:'A',
        skill:'连击2',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:112,max_green:395,min_red:225,max_red:395,
        min_blue:375,max_blue:500,min_purple:225,max_purple:395,
        min_yello:112,max_yello:395,min_black:78,max_black:395
    },
    {
        id:159,name:'牛楠楠改',attribute:'水',shape:'L',
        hp:'A',sp:'A',attack:'A',guard:'S',speed:'B',wisdom:'A',
        skill:'水平攻击3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:377,max_blue:500,min_purple:113,max_purple:397,
        min_yello:38,max_yello:197,min_black:0,max_black:0
    },
    {
        id:160,name:'大佬君改',attribute:'水',shape:'L',
        hp:'A',sp:'A',attack:'A',guard:'A',speed:'A',wisdom:'A',
        skill:'究极攻击3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:80,max_green:395,min_red:50,max_red:395,
        min_blue:0,max_blue:0,min_purple:50,max_purple:395,
        min_yello:80,max_yello:395,min_black:398,max_black:500
    },
    {
        id:161,name:'蛙蛙君改',attribute:'水',shape:'L',
        hp:'A',sp:'C',attack:'B',guard:'B',speed:'B',wisdom:'S',
        skill:'HP回复术3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:39,max_red:198,
        min_blue:81,max_blue:398,min_purple:388,max_purple:500,
        min_yello:39,max_yello:198,min_black:0,max_black:0
    },
    {
        id:162,name:'怪鸟沙沙改',attribute:'雷',shape:'L',
        hp:'A',sp:'B',attack:'A',guard:'A',speed:'S',wisdom:'A',
        skill:'加速之术3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'155',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:383,max_blue:500,min_purple:114,max_purple:393,
        min_yello:38,max_yello:193,min_black:0,max_black:0
    },
    {
        id:163,name:'朵拉卜改',attribute:'火',shape:'L',
        hp:'A',sp:'E',attack:'A',guard:'A',speed:'A',wisdom:'A',
        skill:'水平攻击3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:398,max_green:500,min_red:238,max_red:498,
        min_blue:40,max_blue:198,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:164,name:'风拳龙改',attribute:'木',shape:'L',
        hp:'S',sp:'A',attack:'A',guard:'S',speed:'B',wisdom:'A',
        skill:'究极攻击2',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:39,max_green:295,min_red:57,max_red:495,
        min_blue:57,max_blue:495,min_purple:237,max_purple:495,
        min_yello:395,max_yello:500,min_black:57,max_black:495
    },
    {
        id:165,name:'歪罗王君君改',attribute:'雷',shape:'L',
        hp:'A',sp:'S',attack:'S',guard:'A',speed:'A',wisdom:'B',
        skill:'HP回复术3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:117,max_green:490,min_red:234,max_red:490,
        min_blue:390,max_blue:500,min_purple:234,max_purple:490,
        min_yello:117,max_yello:490,min_black:81,max_black:490
    },
    {
        id:166,name:'烤串大王改',attribute:'暗',shape:'L',
        hp:'S',sp:'B',attack:'A',guard:'A',speed:'S',wisdom:'S',
        skill:'究极攻击2',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:85,max_green:498,min_red:59,max_red:498,
        min_blue:0,max_blue:0,min_purple:59,max_purple:498,
        min_yello:85,max_yello:498,min_black:408,max_black:500
    },
    {
        id:167,name:'欧巴太郎改',attribute:'雷',shape:'L',
        hp:'S',sp:'B',attack:'A',guard:'A',speed:'S',wisdom:'S',
        skill:'水平攻击3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'156',
        min_green:242,max_green:494,min_red:242,max_red:494,
        min_blue:121,max_blue:494,min_purple:404,max_purple:500,
        min_yello:242,max_yello:494,min_black:121,max_black:494
    },
    {
        id:168,name:'火焱龙改',attribute:'火',shape:'L',
        hp:'S',sp:'A',attack:'S',guard:'A',speed:'A',wisdom:'A',
        skill:'究极攻击3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:407,max_red:500,
        min_blue:244,max_blue:497,min_purple:41,max_purple:197,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:169,name:'大舌Z改',attribute:'暗',shape:'L',
        hp:'S',sp:'A',attack:'S',guard:'A',speed:'S',wisdom:'S',
        skill:'究极攻击3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:125,max_green:498,min_red:250,max_red:498,
        min_blue:418,max_blue:500,min_purple:250,max_purple:498,
        min_yello:125,max_yello:498,min_black:87,max_black:498
    },
    {
        id:170,name:'大佬君极',attribute:'水',shape:'L',
        hp:'S',sp:'A',attack:'S',guard:'S',speed:'S',wisdom:'S',
        skill:'究极攻击3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:171,name:'蛙蛙君极',attribute:'木',shape:'L',
        hp:'S',sp:'C',attack:'S',guard:'S',speed:'S',wisdom:'S',
        skill:'HP回复术3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:172,name:'怪鸟沙沙极',attribute:'雷',shape:'L',
        hp:'S',sp:'D',attack:'S',guard:'S',speed:'S',wisdom:'S',
        skill:'加速之术3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:173,name:'朵拉卜极',attribute:'火',shape:'L',
        hp:'S',sp:'E',attack:'S',guard:'S',speed:'S',wisdom:'S',
        skill:'水平攻击3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:174,name:'风拳龙极',attribute:'木',shape:'L',
        hp:'S',sp:'A',attack:'S',guard:'S',speed:'S',wisdom:'S',
        skill:'究极攻击2',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:175,name:'歪罗王王君极',attribute:'雷',shape:'L',
        hp:'S',sp:'S',attack:'S',guard:'S',speed:'S',wisdom:'A',
        skill:'HP回复术3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:176,name:'烤串大王极',attribute:'暗',shape:'L',
        hp:'S',sp:'B',attack:'S',guard:'S',speed:'S',wisdom:'S',
        skill:'究极攻击3\水平',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:177,name:'欧巴太郎极',attribute:'雷',shape:'L',
        hp:'S',sp:'B',attack:'S',guard:'S',speed:'S',wisdom:'S',
        skill:'水平攻击3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:178,name:'火焱龙极',attribute:'火',shape:'L',
        hp:'S',sp:'B',attack:'S',guard:'S',speed:'S',wisdom:'A',
        skill:'究极3\连击',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:179,name:'大舌Z极',attribute:'暗',shape:'L',
        hp:'S',sp:'A',attack:'S',guard:'S',speed:'S',wisdom:'S',
        skill:'究极3\水平',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:180,name:'肩骨龙',attribute:'暗',shape:'L',
        hp:'A',sp:'F',attack:'A',guard:'A',speed:'A',wisdom:'A',
        skill:'连击1',skill_docs:'',
        evolve:'183',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:181,name:'电弩弩',attribute:'雷',shape:'L',
        hp:'A',sp:'S',attack:'A',guard:'S',speed:'B',wisdom:'A',
        skill:'连击1',skill_docs:'',
        evolve:'184',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:182,name:'水仙龙',attribute:'水',shape:'L',
        hp:'S',sp:'S',attack:'B',guard:'A',speed:'A',wisdom:'A',
        skill:'HP回复术1',skill_docs:'',
        evolve:'185',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:183,name:'肩骨龙改',attribute:'暗',shape:'L',
        hp:'S',sp:'B',attack:'S',guard:'S',speed:'S',wisdom:'S',
        skill:'连击1',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'180',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:184,name:'电弩弩改',attribute:'雷',shape:'L',
        hp:'S',sp:'S',attack:'A',guard:'S',speed:'A',wisdom:'S',
        skill:'连击\究极1',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'181',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:185,name:'水仙龙改',attribute:'水',shape:'L',
        hp:'S',sp:'D',attack:'S',guard:'A',speed:'A',wisdom:'A',
        skill:'HP回复术1',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'182',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:186,name:'小开罗君',attribute:'无',shape:'S',
        hp:'C',sp:'B',attack:'D',guard:'C',speed:'C',wisdom:'C',
        skill:'连击1',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:187,name:'蓝色小开罗君',attribute:'水',shape:'S',
        hp:'C',sp:'S',attack:'D',guard:'C',speed:'C',wisdom:'C',
        skill:'加速\究极1',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:188,name:'红色小开罗君',attribute:'火',shape:'S',
        hp:'C',sp:'D',attack:'D',guard:'C',speed:'C',wisdom:'C',
        skill:'究极攻击1',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:189,name:'双星小开罗君',attribute:'雷',shape:'S',
        hp:'B',sp:'C',attack:'C',guard:'B',speed:'B',wisdom:'B',
        skill:'加速之术1',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:190,name:'开罗君',attribute:'木',shape:'M',
        hp:'S',sp:'B',attack:'B',guard:'S',speed:'A',wisdom:'S',
        skill:'水平攻击3',skill_docs:'',
        evolve:'193',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:191,name:'开罗英雄',attribute:'火',shape:'M',
        hp:'S',sp:'A',attack:'A',guard:'A',speed:'A',wisdom:'A',
        skill:'究极攻击3',skill_docs:'',
        evolve:'194',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:192,name:'钻头开罗君',attribute:'雷',shape:'M',
        hp:'S',sp:'S',attack:'S',guard:'A',speed:'A',wisdom:'A',
        skill:'究极攻击3',skill_docs:'',
        evolve:'195',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:193,name:'开罗君改',attribute:'木',shape:'M',
        hp:'S',sp:'D',attack:'B',guard:'S',speed:'S',wisdom:'S',
        skill:'水平攻击3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'190',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:194,name:'开罗英雄改',attribute:'火',shape:'M',
        hp:'S',sp:'S',attack:'S',guard:'S',speed:'S',wisdom:'S',
        skill:'究极攻击3/连击',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'191',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:195,name:'钻头开罗君改',attribute:'雷',shape:'M',
        hp:'S',sp:'S',attack:'S',guard:'S',speed:'A',wisdom:'A',
        skill:'究极攻击3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'192',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
]