export const Kailuo_0821=[
    {
        id:1, // 编号
        name:'波波洛利', //名称
        attribute:'', //属性
        shape:'S', //体型
        hp:'F', //血量
        sp:'E', //疲劳值
        attack:'F',//攻击
        guard:'F', //防御
        speed:'F', //速度
        wisdom:'E',//智力
        skill:'',  //技能
        skill_docs:'',//技能说明
        evolve:6,    //进化
        evolveTwo:19,//最终进化
        vestigial:'',//由谁进化
        vestigialTwo:'',//由谁孵化
        min_green:0,
        max_green:500,
        min_red:0,
        max_red:500,
        min_blue:0,
        max_blue:500,
        min_purple:0,
        max_purple:500,
        min_yello:0,
        max_yello:500,
        min_black:0,
        max_black:500
    },
    {
        id:2,name:'梅塔可',attribute:'',shape:'S',
        hp:'F',sp:'D',attack:'F',guard:'F',speed:'F',wisdom:'E',
        skill:'加速之速I',skill_docs:'',
        evolve:'11',evolveTwo:'13',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:15,max_blue:200,min_purple:4,max_purple:95,
        min_yello:0,max_yello:95,min_black:0,max_black:0
    },
    {
        id:3,name:'小海蛇',attribute:'',shape:'S',
        hp:'F',sp:'E',attack:'F',guard:'F',speed:'F',wisdom:'F',
        skill:'水平攻击I',skill_docs:'',
        evolve:'35',evolveTwo:'69',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:18,max_blue:200,min_purple:5,max_purple:98,
        min_yello:0,max_yello:98,min_black:0,max_black:0
    },
    {
        id:4,name:'淡黄水母',attribute:'水',shape:'S',
        hp:'F',sp:'F',attack:'E',guard:'E',speed:'E',wisdom:'E',
        skill:'加速之术I',skill_docs:'',
        evolve:'14',evolveTwo:'46',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:90,min_red:1,max_red:90,
        min_blue:1,max_blue:90,min_purple:6,max_purple:90,
        min_yello:10,max_yello:200,min_black:1,max_black:90
    },
    {
        id:5,name:'加布龙头鱼',attribute:'水',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:15,max_blue:200,min_purple:4,max_purple:95,
        min_yello:0,max_yello:95,min_black:0,max_black:0
    },
    {
        id:6,name:'水滴君',attribute:'水',shape:'S',
        hp:'F',sp:'D',attack:'F',guard:'E',speed:'E',wisdom:'E',
        skill:'HP回复I',skill_docs:'',
        evolve:'19',evolveTwo:'52',vestigial:'',vestigialTwo:'',
        min_green:19,max_green:200,min_red:9,max_red:95,
        min_blue:0,max_blue:95,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:7,name:'乌贼鲁塔',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:8,name:'卡布林贝',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:9,name:'针左卫门',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:10,name:'奇酷虾',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:11,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:12,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:13,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:14,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:15,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:16,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:17,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:18,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:19,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:20,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:21,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:22,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:23,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:24,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:25,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:26,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:27,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:28,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:29,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:30,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:31,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:32,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:33,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:34,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:35,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:36,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:37,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:38,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:39,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:40,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:41,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:42,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:43,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:44,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:45,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:46,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:47,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:48,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:49,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:50,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:51,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:52,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:53,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:54,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:55,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:56,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:57,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:58,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:59,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:60,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:61,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:62,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:63,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:64,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:65,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:66,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:67,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:68,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:69,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:70,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:71,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:72,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:73,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:74,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:75,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:76,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:77,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:78,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:79,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:80,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:81,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:82,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:83,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:84,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:85,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:86,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:87,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:88,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:89,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:90,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:91,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:92,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:93,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:94,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:95,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:96,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:97,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:98,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:99,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:100,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:101,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:102,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:103,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:104,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:105,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:106,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:107,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:108,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:109,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:110,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:111,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:112,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:113,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:114,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:115,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:116,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:117,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:118,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:119,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:120,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:121,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:122,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:123,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:124,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:125,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:126,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:127,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:128,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:129,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:130,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:131,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:132,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:133,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:134,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:135,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:136,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:137,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:138,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:139,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:140,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:141,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:142,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:143,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:144,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:145,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:146,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:147,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:148,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:149,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:150,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:151,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:152,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:153,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:154,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:155,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:156,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:157,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:158,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:159,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:160,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:161,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:162,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:163,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:164,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:165,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:166,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:167,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:168,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:169,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:0,max_green:0,min_red:0,max_red:0,
        min_blue:0,max_blue:0,min_purple:0,max_purple:0,
        min_yello:0,max_yello:0,min_black:0,max_black:0
    },
    {
        id:170,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:171,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:172,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:173,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:174,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:175,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:176,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:177,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:178,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:179,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:180,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:181,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:182,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:183,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:184,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:185,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:186,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:187,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:188,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:189,name:'',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:190,name:'开罗君',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:191,name:'开罗英雄',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:192,name:'钻头开罗君',attribute:'',shape:'',
        hp:'',sp:'',attack:'',guard:'',speed:'',wisdom:'',
        skill:'',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:193,name:'开罗君改',attribute:'木',shape:'M',
        hp:'S',sp:'D',attack:'B',guard:'S',speed:'S',wisdom:'S',
        skill:'水平攻击3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'190',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:194,name:'开罗英雄改',attribute:'火',shape:'M',
        hp:'S',sp:'S',attack:'S',guard:'S',speed:'S',wisdom:'S',
        skill:'究极攻击3/连击',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'191',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
    {
        id:195,name:'钻头开罗君改',attribute:'雷',shape:'M',
        hp:'S',sp:'S',attack:'S',guard:'S',speed:'A',wisdom:'A',
        skill:'究极攻击3',skill_docs:'',
        evolve:'',evolveTwo:'',vestigial:'192',vestigialTwo:'',
        min_green:1000,max_green:1000,min_red:1000,max_red:1000,
        min_blue:1000,max_blue:1000,min_purple:1000,max_purple:1000,
        min_yello:1000,max_yello:1000,min_black:1000,max_black:1000
    },
]