/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    0821Header: typeof import('./components/0821Header.vue')['default']
    '副本': typeof import('./components/Header_0821 - 副本.vue')['default']
    Header_0821: typeof import('./components/Header_0821.vue')['default']
    Header_0823: typeof import('./components/Header_0823.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanField: typeof import('vant/es')['Field']
  }
}
